name: iskcon_appl
description: A new Flutter project.

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.1.0
  audioplayers: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/brown_logo_crop.png
    - assets/aes_black_krish.jpg
    - assets/1.mp3
    - assets/2.m4a
    - assets/3.m4a
    - assets/4.m4a
    - assets/5.m4a
    - assets/6.m4a
    - assets/7.m4a
    - assets/8.m4a
    - assets/9.m4a
    - assets/10.m4a
    - assets/11.m4a
